<Project>
  <PropertyGroup Condition="'$(Configuration)' == 'Mono'">
    <GamePath>$MONO_GAME_DIR$</GamePath>
$MONO_REFERENCE_PATHS$
    <DeployOnBuild>$MONO_DEPLOY_ON_BUILD$</DeployOnBuild>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Il2Cpp'">
    <GamePath>$IL2CPP_GAME_DIR$</GamePath>
$IL2CPP_REFERENCE_PATHS$
    <DeployOnBuild>$IL2CPP_DEPLOY_ON_BUILD$</DeployOnBuild>
  </PropertyGroup>
</Project>
